/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author frank
 */
public class culminating extends javax.swing.JFrame {
    int xint1,xint2,yint1,yint2,c1,c2;
    double xintercept,yintercept;
    

    /**
     * Creates new form culminating
     */
    public culminating() {
        
        initComponents();
        btnsubmit.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtquestion = new javax.swing.JTextArea();
        btnstart = new javax.swing.JToggleButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtoutput = new javax.swing.JTextArea();
        txtinputx = new javax.swing.JTextField();
        txtinputy = new javax.swing.JTextField();
        btnsubmit = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Linear Solver Question Bank");

        txtquestion.setEditable(false);
        txtquestion.setColumns(20);
        txtquestion.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        txtquestion.setForeground(java.awt.Color.red);
        txtquestion.setLineWrap(true);
        txtquestion.setRows(5);
        txtquestion.setToolTipText("");
        txtquestion.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtquestion);

        btnstart.setText("Randomize");
        btnstart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnstartActionPerformed(evt);
            }
        });

        txtoutput.setEditable(false);
        txtoutput.setColumns(20);
        txtoutput.setLineWrap(true);
        txtoutput.setRows(5);
        txtoutput.setWrapStyleWord(true);
        jScrollPane2.setViewportView(txtoutput);

        btnsubmit.setText("Submit");
        btnsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubmitActionPerformed(evt);
            }
        });

        jLabel2.setText("Enter Answer for X intercept above 2 decimal if necessary");

        jLabel3.setText("Enter Answer for y intercept above 2 decimal if necessary");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(144, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(117, 117, 117))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(btnstart))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtinputy, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtinputx, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(41, 41, 41)
                        .addComponent(btnsubmit)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(btnstart)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtinputx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnsubmit)
                        .addGap(5, 5, 5)))
                .addComponent(txtinputy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnstartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnstartActionPerformed
    btnsubmit.setEnabled(true);//enables the submit button upon press
    txtquestion.setText("");//clears all the boxes on the interface except for the questions
    txtoutput.setText("");
    txtinputx.setText("");
    txtinputy.setText("");
    do{
       xint1=(int)(Math.random()*100+1);//these 4 lines provide a randomly generated number for the linear function
       xint2=(int)(Math.random()*100+1);
       yint1=(int)(Math.random()*100+1);
       yint2=(int)(Math.random()*100+1);
       c1=(int)(Math.random()*100+1);
       c2=(int)(Math.random()*100+1);
    }while((xint1*yint2)-(xint2*yint1)==0);//Cramer's law states that ths function is solvable as long as the difference between the product of x variable and y variables of opposite functions do not equal 0
   txtquestion.append("1) "+xint1+"x+"+yint1+"y="+c1+"\n");//outputs the two functions generated
   txtquestion.append("2) "+xint2+"x+"+yint2+"y="+c2);
   xintercept=(Math.round(calculatex()*100.0))/100.0;//takes calculations and rounds it to 2 decimal places
   yintercept=(Math.round(calculatey()*100.0))/100.0;
   
    
    }//GEN-LAST:event_btnstartActionPerformed

    private void btnsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubmitActionPerformed
       double x,y;
       txtoutput.setText("");//clears the output box each time submit is pressed
       x=Double.parseDouble(txtinputx.getText());//takes the user input for x value
       y=Double.parseDouble(txtinputy.getText());//takes the user input for y value
       if(x==xintercept&&y==yintercept){//if the answer inputted match the answer outputted, it send a statement stating correct
           txtoutput.setText("Correct!");
       }
       else{//if the answers are wrong, it states that it is incorrect and provides the right answer
           txtoutput.append("Incorrect Answer\n");
           txtoutput.append("your Answer: x="+x+" y="+y+"\n");
           txtoutput.append("Correct Answer: x="+xintercept+" y="+yintercept);
           
       }
       
    }//GEN-LAST:event_btnsubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(culminating.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(culminating.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(culminating.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(culminating.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new culminating().setVisible(true);
            }
        });
    }
    public double calculatex(){
       double x;
       x=(double)(c1*yint2-yint1*c2)/(xint1*yint2-yint1*xint2);//solves for the x intercept using Cramer's law
       return x;//returns the x value calculated 
    }
    public double calculatey(){
        double y;
        y=(double)(xint1*c2-c1*xint2)/(xint1*yint2-yint1*xint2);
        return y;//returns the x value calculated
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnstart;
    private javax.swing.JToggleButton btnsubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtinputx;
    private javax.swing.JTextField txtinputy;
    private javax.swing.JTextArea txtoutput;
    private javax.swing.JTextArea txtquestion;
    // End of variables declaration//GEN-END:variables
}
